# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f996d613aee1bf96b07840d85cbf88bf3c93d04102b57601020194d654924819df3cb3f7b04040ef3603e9cd6b0a2d5e56623b2e51aa37fd051e3b73cf8fed98

test:
  secret_key_base: cd916e183f48bbb501e0091caeca4a6134b910763ecb03e03dbe07cb29aabea1840a017fc64271929f6bc2a13c15d47a5036491144e8dbea98306b8a12418025

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
